"""
微信朋友圈完整导出（含本地缓存图片 + 视频）
支持按用户分文件导出，每人一个独立 HTML
"""
import sqlite3
import xml.etree.ElementTree as ET
import datetime
import re
import json
import os
import sys
import shutil
from collections import defaultdict
from pathlib import Path

import argparse
from config import load_config as _load_config

_cfg = _load_config()
_script_dir = os.path.dirname(os.path.abspath(__file__))
_export_base = os.path.expanduser(_cfg.get('moments_export_dir', '~/moments_export_full'))
_decrypted_dir = _cfg.get('decrypted_dir', os.path.join(_script_dir, 'decrypted'))

DB_PATH = os.path.join(_decrypted_dir, 'sns', 'sns.db')
IMAGES_DIR = os.path.join(_export_base, 'images')
VIDEOS_DIR = os.path.expanduser(_cfg.get('cache_dir', ''))
SNS_DECODED_DIR = os.path.join(_cfg.get('decoded_image_dir', os.path.join(_script_dir, 'decoded_images')), 'sns')
OUT_PATH = os.path.join(_export_base, 'moments_full.html')
BY_USER_DIR = os.path.join(_export_base, 'by_user')

# Relative path from HTML to images (HTML is in moments_export_full/)
IMG_REL = 'images'


def parse_moment(content):
    try:
        root = ET.fromstring(content)
    except ET.ParseError:
        return None

    obj = root.find('TimelineObject')
    extra = root.find('LocalExtraInfo')
    if obj is None:
        return None

    post_id = obj.findtext('id', '')
    username = obj.findtext('username', '')
    ts = obj.findtext('createTime', '0')
    dt = datetime.datetime.fromtimestamp(int(ts)) if ts and ts.isdigit() else None
    text = obj.findtext('contentDesc', '').strip()
    content_type = obj.findtext('.//ContentObject/type', '0')

    nickname = ''
    if extra is not None:
        nickname = extra.findtext('nickname', '')

    loc = obj.find('location')
    location = ''
    if loc is not None:
        location = loc.get('poiName', '') or ''

    media_items = []
    for media in obj.findall('.//mediaList/media'):
        mtype = media.findtext('type', '0')
        thumb_el = media.find('thumb')
        url_el = media.find('url')
        thumb_url = thumb_el.text if thumb_el is not None else ''
        full_url = url_el.text if url_el is not None else ''
        thumb_md5 = thumb_el.get('md5', '') if thumb_el is not None else ''
        full_md5 = url_el.get('md5', '') if url_el is not None else ''
        videomd5 = url_el.get('videomd5', '') if url_el is not None else ''
        size_el = media.find('size')
        w = size_el.get('width', '') if size_el is not None else ''
        h = size_el.get('height', '') if size_el is not None else ''
        media_items.append({
            'type': mtype,
            'thumb': thumb_url,
            'url': full_url,
            'thumb_md5': thumb_md5,
            'full_md5': full_md5,
            'videomd5': videomd5,
            'width': w,
            'height': h,
        })

    link_title = obj.findtext('.//appInfo/title', '') or obj.findtext('.//title', '')
    link_desc = obj.findtext('.//appInfo/desc', '') or obj.findtext('.//desc', '')
    link_url = obj.findtext('.//appInfo/url', '') or obj.findtext('.//url', '')

    likes = []
    for u in obj.findall('.//likeUserList/likeUser'):
        n = u.findtext('nickName', '')
        if n:
            likes.append(n)

    comments = []
    for c in obj.findall('.//commentList/comment'):
        cfrom = c.findtext('nickName', '') or c.findtext('username', '')
        ctxt = c.findtext('content', '')
        reply_to = c.findtext('replyCommentNickName', '')
        if ctxt:
            comments.append({'from': cfrom, 'text': ctxt, 'reply_to': reply_to})

    return {
        'id': post_id,
        'username': username,
        'nickname': nickname or username,
        'time': dt,
        'text': text,
        'type': content_type,
        'media': media_items,
        'location': location,
        'likes': likes,
        'comments': comments,
        'link_title': link_title,
        'link_desc': link_desc,
        'link_url': link_url,
    }


def build_local_image_index():
    """Build MD5 -> filename index from decoded_images/sns/ directory.
    
    First tries to load md5_index.json (content md5 -> filename),
    which is generated by computing md5 of decrypted image contents.
    Falls back to filename-based index if not available.
    """
    index = {}
    md5_index_path = os.path.join(os.path.dirname(SNS_DECODED_DIR), 'md5_index.json')
    if os.path.exists(md5_index_path):
        try:
            with open(md5_index_path, 'r') as f:
                index = json.load(f)
            return index
        except Exception:
            pass
    
    # Fallback: filename-based index (may not match XML md5s)
    if not os.path.exists(SNS_DECODED_DIR):
        return index
    for fname in os.listdir(SNS_DECODED_DIR):
        if '.' not in fname:
            continue
        base = fname.rsplit('.', 1)[0]
        ext = fname.rsplit('.', 1)[1].lower()
        if ext in ('jpg', 'jpeg', 'png', 'webp', 'gif', 'hevc'):
            index[base] = fname
    return index


def load_image_index_by_month():
    """Load image_index.jsonl and group by month.
    If the index file doesn't exist, auto-generate it by scanning cache dir.
    Returns: {month: [filename, ...]}
    """
    # Try script dir first (survives rm -rf of export dir)
    index_file = os.path.join(_script_dir, 'image_index.jsonl')
    if not os.path.exists(index_file):
        index_file = os.path.join(_export_base, 'image_index.jsonl')
    
    by_month = defaultdict(list)
    
    # Auto-generate if not exists
    if not os.path.exists(index_file):
        print("自动生成图片月份索引...")
        cache_base = _cfg.get('cache_dir', '')
        if cache_base and os.path.exists(cache_base):
            for root, dirs, files in os.walk(cache_base):
                if 'Sns/Img' not in root:
                    continue
                for fname in files:
                    if '.' in fname:
                        continue
                    for ext in ('jpg', 'jpeg', 'png', 'webp', 'gif', 'hevc'):
                        dec_path = os.path.join(SNS_DECODED_DIR, f'{fname}.{ext}')
                        if os.path.exists(dec_path):
                            month = 'unknown'
                            for p in root.split(os.sep):
                                if len(p) == 7 and p[4] == '-':
                                    month = p
                                    break
                            by_month[month].append(f'{fname}.{ext}')
                            break
            # Save for next time
            try:
                with open(index_file, 'w', encoding='utf-8') as f:
                    for month, files in by_month.items():
                        for fname in files:
                            f.write(json.dumps({'file': fname, 'month': month}, ensure_ascii=False) + '\n')
                print(f"  索引已保存: {index_file}")
            except Exception as e:
                print(f"  索引保存失败: {e}")
        return by_month
    
    # Load existing index
    with open(index_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
                month = entry.get('month', 'unknown')
                fname = entry.get('file', '')
                if fname:
                    by_month[month].append(fname)
            except Exception:
                pass
    return by_month


def copy_image_to_export(md5, local_index):
    """Copy a local decoded image to the export images dir, return relative filename."""
    if not md5 or md5 not in local_index:
        return None
    src = os.path.join(SNS_DECODED_DIR, local_index[md5])
    fname = local_index[md5]
    dst = os.path.join(IMAGES_DIR, fname)
    if not os.path.exists(dst):
        os.makedirs(IMAGES_DIR, exist_ok=True)
        shutil.copy2(src, dst)
    return fname


def copy_decoded_image_to_export(fname):
    """Copy a specific decoded image file to the export images dir."""
    src = os.path.join(SNS_DECODED_DIR, fname)
    if not os.path.exists(src):
        return None
    dst = os.path.join(IMAGES_DIR, fname)
    if not os.path.exists(dst):
        os.makedirs(IMAGES_DIR, exist_ok=True)
        shutil.copy2(src, dst)
    return fname


def esc(s):
    return (s or '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def moment_html(m, idx, local_index, img_rel='images', month_images=None):
    time_str = m['time'].strftime('%Y年%m月%d日 %H:%M') if m['time'] else '未知时间'
    date_str = m['time'].strftime('%Y-%m-%d') if m['time'] else ''

    avatar_char = (m['nickname'] or '?')[0]
    color_idx = sum(ord(c) for c in (m['username'] or '?')) % 8
    colors = ['#FF6B6B','#4ECDC4','#45B7D1','#96CEB4','#FFEAA7','#DDA0DD','#98D8C8','#F7DC6F']
    avatar_color = colors[color_idx]

    text_html = ''
    if m['text']:
        text_html = f'<div class="post-text">{esc(m["text"]).replace(chr(10), "<br>")}</div>'

    media_html = ''
    images = [mv for mv in m['media'] if mv['type'] in ('2', '1')]
    # 视频判断：media.type == '6' 且 ContentObject.type == '15'，或者 media type 为 '15'
    videos = [mv for mv in m['media'] if mv['type'] == '15' or (m['type'] == '15' and mv['type'] == '6')]

    # Get month key for fallback local images
    month_key = m['time'].strftime('%Y-%m') if m['time'] else None
    fallback_pool = month_images.get(month_key, []) if month_images else []
    fallback_idx = [0]  # use list for mutable closure

    def get_fallback_image():
        if fallback_idx[0] < len(fallback_pool):
            fname = fallback_pool[fallback_idx[0]]
            fallback_idx[0] += 1
            copied = copy_decoded_image_to_export(fname)
            if copied:
                return f'{img_rel}/{copied}'
        return None

    if images:
        n = len(images)
        grid_class = f'grid-{min(n, 3)}'
        img_tags = ''
        for mv in images:
            # Try local images first (md5 match)
            thumb_local = copy_image_to_export(mv['thumb_md5'], local_index)
            full_local = copy_image_to_export(mv['full_md5'], local_index)

            if thumb_local:
                src = f'{img_rel}/{thumb_local}'
                full = f'{img_rel}/{thumb_local}'
            elif full_local:
                src = f'{img_rel}/{full_local}'
                full = f'{img_rel}/{full_local}'
            else:
                # Fallback: use local month images instead of CDN
                local_src = get_fallback_image()
                if local_src:
                    src = local_src
                    full = local_src
                else:
                    src = mv['thumb'] or mv['url']
                    full = mv['url'] or mv['thumb']

            if src:
                is_local = thumb_local or full_local or local_src
                onerror = '' if is_local else 'onerror="this.style.display=\'none\';this.parentNode.classList.add(\'img-dead\')"'
                img_tags += (
                    f'<a href="{esc(full)}" target="_blank">'
                    f'<img src="{esc(src)}" loading="lazy" {onerror}>'
                    f'</a>'
                )
            else:
                img_tags += f'<div class="img-placeholder">🖼</div>'
        media_html = f'<div class="media-grid {grid_class}">{img_tags}</div>'

    if videos:
        for mv in videos:
            thumb_local = copy_image_to_export(mv['thumb_md5'], local_index)
            poster = f'{img_rel}/{thumb_local}' if thumb_local else (mv['thumb'] or '')
            video_src = mv['url'] or mv['thumb'] or ''
            if video_src:
                media_html += (
                    f'<div class="video-wrapper">'
                    f'<video controls preload="none" poster="{esc(poster)}" style="max-width:100%;border-radius:6px;">'
                    f'<source src="{esc(video_src)}" type="video/mp4">'
                    f'</video>'
                    f'</div>'
                )
            elif poster:
                media_html += (
                    f'<div class="video-placeholder">'
                    f'<img src="{esc(poster)}" loading="lazy" '
                    f'onerror="this.closest(\'.video-placeholder\').innerHTML=\'🎬 视频\'">'
                    f'<span class="play-icon">▶</span></div>'
                )

    link_html = ''
    if m['link_title']:
        href = esc(m['link_url'] or '#')
        link_html = f'''<a class="link-card" href="{href}" target="_blank">
            <div class="link-title">{esc(m["link_title"])}</div>
            <div class="link-desc">{esc(m["link_desc"] or "")}</div>
        </a>'''

    loc_html = f'<span class="location">📍 {esc(m["location"])}</span>' if m['location'] else ''

    likes_html = ''
    if m['likes']:
        likes_html = f'<div class="likes">❤ {esc("、".join(m["likes"]))}</div>'

    comments_html = ''
    if m['comments']:
        items = ''
        for c in m['comments']:
            fn = esc(c['from'])
            ct = esc(c['text']).replace('\n', '<br>')
            if c['reply_to']:
                rt = esc(c['reply_to'])
                items += f'<div class="comment"><span class="cfrom">{fn}</span> 回复 <span class="cfrom">{rt}</span>：{ct}</div>'
            else:
                items += f'<div class="comment"><span class="cfrom">{fn}</span>：{ct}</div>'
        comments_html = f'<div class="comments">{items}</div>'

    return f'''<article class="post" id="post-{idx}" data-date="{date_str}">
  <div class="post-header">
    <div class="avatar" style="background:{avatar_color}">{esc(avatar_char)}</div>
    <div class="post-meta">
      <span class="nickname">{esc(m["nickname"])}</span>
      <span class="post-time">{time_str}</span>
      {loc_html}
    </div>
  </div>
  <div class="post-body">
    {text_html}
    {media_html}
    {link_html}
  </div>
  {likes_html}
  {comments_html}
</article>'''


def build_html(content_html, title, subtitle, img_rel='images'):
    """Generate a complete HTML page."""
    return f'''<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title>
<style>{CSS}</style>
</head>
<body>
<header>
  <h1>📱 {esc(title)}</h1>
  <p>{esc(subtitle)}</p>
</header>
<div class="filterbar">
  <input type="text" id="search" placeholder="搜索文字内容..." oninput="doSearch(this.value)">
</div>
<div class="timeline" id="timeline">
{content_html}
</div>
<button id="backtop" onclick="window.scrollTo({{top:0,behavior:'smooth'}})">↑</button>
<script>{JS}</script>
</body>
</html>'''


def user_list_html(users):
    """Generate the overview index page listing all users."""
    items = ''
    for username, info in sorted(users.items(), key=lambda x: x[1]['count'], reverse=True):
        nickname = info['nickname'] or username
        count = info['count']
        date_range = info['date_range']
        avatar_char = (nickname or '?')[0]
        color_idx = sum(ord(c) for c in (username or '?')) % 8
        colors = ['#FF6B6B','#4ECDC4','#45B7D1','#96CEB4','#FFEAA7','#DDA0DD','#98D8C8','#F7DC6F']
        avatar_color = colors[color_idx]
        items += (
            f'<a class="user-card" href="by_user/{username}.html">'
            f'<div class="avatar" style="background:{avatar_color}">{esc(avatar_char)}</div>'
            f'<div class="user-info">'
            f'<div class="nickname">{esc(nickname)}</div>'
            f'<div class="stats">{count} 条朋友圈 · {date_range}</div>'
            f'</div></a>'
        )

    content = f'<div class="user-list">{items}</div>'
    return build_html(content, '朋友圈好友列表', f'共 {len(users)} 位好友')


CSS = '''
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,"PingFang SC","Microsoft YaHei",sans-serif;background:#1a1a1a;color:#e0e0e0}
header{background:#111;padding:14px 20px;position:sticky;top:0;z-index:100;border-bottom:1px solid #333}
header h1{font-size:18px;color:#fff}
header p{font-size:13px;color:#888;margin-top:4px}
.filterbar{background:#111;padding:8px 16px;border-bottom:1px solid #333;display:flex;gap:8px;flex-wrap:wrap}
.filterbar input{background:#2a2a2a;border:1px solid #444;color:#e0e0e0;padding:6px 12px;border-radius:20px;font-size:13px;width:220px}
.filterbar input::placeholder{color:#666}
.timeline{max-width:700px;margin:0 auto;padding:16px}
.date-divider{text-align:center;margin:24px 0 10px;position:relative}
.date-divider::before{content:'';position:absolute;left:0;right:0;top:50%;height:1px;background:#333}
.date-divider span{background:#1a1a1a;padding:0 12px;position:relative;font-size:12px;color:#666}
.month-gallery{background:#1e2a1e;border:1px solid #2a4a2a;border-radius:10px;margin:12px 0 20px;padding:12px}
.gallery-title{font-size:13px;color:#6a9;margin-bottom:8px;font-weight:600;cursor:pointer;user-select:none}
.gallery-title:hover{color:#8cb}
.gallery-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:3px}
.gallery-grid a{display:block;aspect-ratio:1;overflow:hidden;background:#333;border-radius:3px}
.gallery-grid img{width:100%;height:100%;object-fit:cover;transition:transform .2s}
.gallery-grid a:hover img{transform:scale(1.06)}
.video-gallery{background:#1e1e2a;border:1px solid #2a2a4a;border-radius:10px;margin:12px 0 20px;padding:12px}
.video-gallery-title{font-size:13px;color:#79f;margin-bottom:8px;font-weight:600}
.video-grid{display:flex;gap:8px;flex-wrap:wrap}
.video-item{position:relative;width:160px;border-radius:6px;overflow:hidden;background:#000}
.video-item video{width:100%;display:block}
.post{background:#242424;border-radius:12px;margin-bottom:10px;padding:14px;border:1px solid #333}
.post:hover{border-color:#555}
.post-header{display:flex;gap:10px;margin-bottom:10px}
.avatar{width:40px;height:40px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:bold;color:#fff;flex-shrink:0}
.post-meta{flex:1}
.nickname{display:block;font-size:15px;font-weight:600;color:#7eb8f7}
.post-time{display:block;font-size:12px;color:#666;margin-top:2px}
.location{font-size:11px;color:#888;display:block;margin-top:1px}
.post-body{margin-left:50px}
.post-text{font-size:15px;line-height:1.6;color:#ddd;margin-bottom:8px;word-break:break-word}
.media-hint{font-size:12px;color:#666;background:#2a2a2a;padding:4px 8px;border-radius:4px;display:inline-block;margin-bottom:6px}
.img-placeholder{aspect-ratio:1;background:#2a2a2a;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:24px;color:#555}
.img-dead{background:#1e1e1e;aspect-ratio:1;border-radius:4px;display:flex;align-items:center;justify-content:center}
.img-dead::after{content:"🖼";font-size:20px;opacity:0.3}
.media-grid{display:grid;gap:3px;margin-bottom:8px}
.media-grid.grid-1{grid-template-columns:1fr;max-width:320px}
.media-grid.grid-2{grid-template-columns:1fr 1fr;max-width:320px}
.media-grid.grid-3,.media-grid.grid-4{grid-template-columns:repeat(3,1fr);max-width:360px}
.media-grid a{display:block;aspect-ratio:1;overflow:hidden;background:#333;border-radius:4px}
.media-grid.grid-1 a{aspect-ratio:auto;max-height:400px}
.media-grid img{width:100%;height:100%;object-fit:cover;transition:transform .2s}
.media-grid.grid-1 img{object-fit:contain;background:#1a1a1a}
.media-grid a:hover img{transform:scale(1.03)}
.video-placeholder{position:relative;display:inline-block;max-width:200px;margin-bottom:8px;border-radius:6px;overflow:hidden;background:#000}
.video-placeholder img{width:100%;display:block;object-fit:cover}
.video-wrapper{margin-bottom:8px;max-width:320px}
.video-wrapper video{width:100%;border-radius:6px;display:block}
.play-icon{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:32px;color:#fff;text-shadow:0 0 8px rgba(0,0,0,.8);pointer-events:none}
.month-gallery{background:#1a2a1a;border:1px solid #243024;border-radius:8px;margin:4px 0 16px;padding:8px}
.gallery-title{font-size:12px;color:#4a7;margin-bottom:6px;font-weight:500;cursor:pointer;user-select:none}
.gallery-title:hover{color:#6b9}
.gallery-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:2px;display:none}
.link-card{display:block;background:#1e1e1e;border:1px solid #444;border-radius:8px;padding:10px 12px;margin-bottom:8px;text-decoration:none;color:inherit}
.link-card:hover{border-color:#666}
.link-title{font-size:14px;color:#7eb8f7;font-weight:500;margin-bottom:3px}
.link-desc{font-size:12px;color:#888}
.likes{margin-left:50px;font-size:13px;color:#e87070;padding:6px 0;border-top:1px solid #333;margin-top:6px}
.comments{margin-left:50px;background:#1e1e1e;border-radius:6px;padding:8px;margin-top:4px}
.comment{font-size:13px;color:#ccc;padding:2px 0;line-height:1.5}
.cfrom{color:#7eb8f7;font-weight:500}
.hidden{display:none!important}
#backtop{position:fixed;bottom:20px;right:20px;background:#444;color:#fff;border:none;border-radius:50%;width:44px;height:44px;font-size:20px;cursor:pointer;opacity:0;transition:opacity .3s}
#backtop.show{opacity:1}
.user-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px;max-width:900px;margin:0 auto;padding:16px}
.user-card{display:flex;gap:12px;align-items:center;background:#242424;border:1px solid #333;border-radius:12px;padding:14px;text-decoration:none;color:inherit;transition:border-color .2s}
.user-card:hover{border-color:#555}
.user-info{flex:1}
.user-info .nickname{font-size:15px;font-weight:600;color:#7eb8f7}
.user-info .stats{font-size:12px;color:#888;margin-top:4px}
'''

JS = '''
window.addEventListener('scroll',()=>{
  document.getElementById('backtop').classList.toggle('show',window.scrollY>400);
});
function doSearch(q){
  q=q.trim().toLowerCase();
  document.querySelectorAll('.post').forEach(el=>{
    if(!q){el.classList.remove('hidden');return;}
    el.classList.toggle('hidden',!el.textContent.toLowerCase().includes(q));
  });
  document.querySelectorAll('.date-divider').forEach(el=>{
    const sib=el.nextElementSibling;
    if(sib&&sib.classList.contains('hidden'))el.classList.add('hidden');
    else el.classList.remove('hidden');
  });
}
function toggleGallery(el){
  const grid=el.nextElementSibling;
  if(grid)grid.style.display=grid.style.display==='grid'?'none':'grid';
}
'''


def main():
    parser = argparse.ArgumentParser(description='导出微信朋友圈为 HTML')
    parser.add_argument('--user', help='只导出指定用户（wxid）')
    parser.add_argument('--merged', action='store_true', help='同时生成合并版 moments_full.html')
    args = parser.parse_args()

    print("读取朋友圈数据库...")
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute('SELECT tid, user_name, content FROM SnsTimeLine ORDER BY tid ASC')
    rows = cur.fetchall()
    conn.close()
    print(f"  共 {len(rows)} 条记录，解析中...")

    moments = []
    for tid, user, content in rows:
        if not content:
            continue
        m = parse_moment(content)
        if m:
            moments.append(m)

    moments.sort(key=lambda x: x['time'] or datetime.datetime.min)
    print(f"  解析成功 {len(moments)} 条")

    # Build local image index
    print(f"扫描本地解密图片...")
    local_index = build_local_image_index()
    print(f"  找到 {len(local_index)} 张本地图片")

    # Group by user
    by_user = defaultdict(list)
    for m in moments:
        by_user[m['username']].append(m)

    # Filter if --user specified
    target_users = [args.user] if args.user else list(by_user.keys())
    if args.user and args.user not in by_user:
        print(f"[!] 未找到用户: {args.user}")
        sys.exit(1)

    os.makedirs(BY_USER_DIR, exist_ok=True)

    # Load month-grouped image index for gallery
    print("加载本地图片索引...")
    images_by_month = load_image_index_by_month()
    print(f"  共 {sum(len(v) for v in images_by_month.values())} 张图片，{len(images_by_month)} 个月份")

    # Stats for each user
    user_stats = {}
    total_local_hits = 0
    total_local_miss = 0

    for username in target_users:
        user_moments = by_user[username]
        nickname = user_moments[0]['nickname'] if user_moments else username

        # Prepare month-based fallback images for this user
        user_months = set()
        for m in user_moments:
            if m['time']:
                user_months.add(m['time'].strftime('%Y-%m'))
        
        # Build a deterministic fallback pool per month (sorted for consistency)
        month_images = {}
        for month in user_months:
            if month in images_by_month:
                month_images[month] = sorted(images_by_month[month])

        html_parts = []
        last_date = None
        local_hits = 0
        local_miss = 0
        fallback_hits = 0

        for idx, m in enumerate(user_moments):
            date_str = m['time'].strftime('%Y年%m月%d日') if m['time'] else '未知日期'
            if date_str != last_date:
                html_parts.append(f'<div class="date-divider"><span>{date_str}</span></div>')
                last_date = date_str
            html_parts.append(moment_html(m, idx, local_index, img_rel='../images', month_images=month_images))

            for mv in m['media']:
                if mv['type'] in ('2', '1'):
                    if mv['thumb_md5'] in local_index or mv['full_md5'] in local_index:
                        local_hits += 1
                    else:
                        local_miss += 1
                        # Check if fallback was used
                        month_key = m['time'].strftime('%Y-%m') if m['time'] else None
                        if month_key and month_key in month_images and len(month_images[month_key]) > 0:
                            fallback_hits += 1

        # Build month gallery HTML (appendix)
        gallery_html = ''
        matched_months = sorted(user_months & set(images_by_month.keys()), reverse=True)
        if matched_months:
            gallery_sections = []
            for month in matched_months:
                files = images_by_month[month]
                img_tags = ''
                for fname in files[:200]:
                    copied = copy_decoded_image_to_export(fname)
                    if copied:
                        img_tags += f'<a href="../images/{copied}" target="_blank"><img src="../images/{copied}" loading="lazy"></a>'
                if img_tags:
                    yr, mo = month.split('-')
                    title = f'📁 {yr}年{mo}月本地缓存 · {len(files)} 张（点击展开）'
                    gallery_sections.append(
                        f'<div class="month-gallery">'
                        f'<div class="gallery-title" onclick="toggleGallery(this)">{title}</div>'
                        f'<div class="gallery-grid">{img_tags}</div>'
                        f'</div>'
                    )
            if gallery_sections:
                gallery_html = (
                    '<div class="date-divider"><span>本地缓存图片</span></div>'
                    + '\n'.join(gallery_sections)
                )

        content_html = '\n'.join(html_parts)
        if gallery_html:
            content_html += '\n' + gallery_html

        valid_times = [m['time'] for m in user_moments if m['time']]
        if valid_times:
            oldest = min(valid_times).strftime('%Y.%m.%d')
            newest = max(valid_times).strftime('%Y.%m.%d')
            date_range = f'{oldest} – {newest}'
        else:
            date_range = ''

        user_path = os.path.join(BY_USER_DIR, f'{username}.html')
        html = build_html(
            content_html,
            f'{nickname} 的朋友圈',
            f'共 {len(user_moments)} 条 · {date_range}',
            img_rel='../images'
        )
        with open(user_path, 'w', encoding='utf-8') as f:
            f.write(html)

        user_stats[username] = {
            'nickname': nickname,
            'count': len(user_moments),
            'date_range': date_range,
        }
        total_local_hits += local_hits
        total_local_miss += local_miss
        print(f"  ✓ {esc(nickname)} ({username}): {len(user_moments)} 条 · md5命中:{local_hits} · 月份回退:{fallback_hits} · 缺失:{local_miss-fallback_hits} → {user_path}")

    # Generate overview index
    if not args.user:
        index_path = os.path.join(_export_base, 'index.html')
        html = user_list_html(user_stats)
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"\n📋 总览页: {index_path}")

    # Optionally generate merged version
    if args.merged and not args.user:
        print("\n生成合并版...")
        html_parts = []
        last_date = None
        for idx, m in enumerate(moments):
            date_str = m['time'].strftime('%Y年%m月%d日') if m['time'] else '未知日期'
            if date_str != last_date:
                html_parts.append(f'<div class="date-divider"><span>{date_str}</span></div>')
                last_date = date_str
            html_parts.append(moment_html(m, idx, local_index, img_rel='images'))

        content_html = '\n'.join(html_parts)
        valid_times = [m['time'] for m in moments if m['time']]
        date_range = ''
        if valid_times:
            date_range = f'{min(valid_times).strftime("%Y.%m.%d")} – {max(valid_times).strftime("%Y.%m.%d")}'

        html = build_html(content_html, '朋友圈归档', f'共 {len(moments)} 条 · {date_range}', img_rel='images')
        with open(OUT_PATH, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"  合并版: {OUT_PATH}")

    print(f"\n✅ 导出完成")
    print(f"   共 {len(user_stats)} 位用户")
    print(f"   本地图片命中：{total_local_hits}，缺失：{total_local_miss}")
    print(f"   输出目录：{_export_base}")


if __name__ == '__main__':
    main()
